### PR TITLE
Add style.tex

### PR DESCRIPTION
**Pull request by mszep**
This attempts to produce the same style as style.css, but for a
ConTeXt document, which produces a nice pdf.

The commands to produce the pdf are

```
pandoc --standalone --template style.tex \
--from markdown --to context \
-V papersize=A4 \
-o resume.tex
context resume.tex
```

I thought you might like this, let me know what you think :-)

### CODE REVIEW

**Comment by chmduquesne** [comment]
Sorry that I did not get back to you earlier. That is awesome! I will
include it in the project. Thanks for contributing!

**Comment by mszep** [comment]
Just to let you know, I had assumed you weren't interested in this, but some other people might be, so I have put together a repo with a short, generic resume, some instructions, the two style files and a Makefile. People might be more willing to contribute if the repo doesn't look like someone's personal resume repo...

I presume it's OK if I release the style.tex file under the same license as your style.css (which I have slightly modified)? I am using MIT license for the rest of the code, which isn't much at all...

The repo is https://github.com/mszep/pandoc_resume and I also am working on a github pages branch to set up a short page with instructions and examples of the results.

I hope you don't mind me setting up my own project for this! I thought you weren't interested or didn't have time...

**Comment by chmduquesne** [comment]
Absolutely, you did the right thing! It makes much more sense to set up a generic repo rather than forking my resume.

**Comment by mszep** [comment]
Blog post is done at http://mszep.github.io/pandoc_resume/

I've submitted it to hacker news, and at least a few people seem to like it..
If you have any remarks, let me know :-)

**Pull request merged**
